<a href="https://colab.research.google.com/github/msaid1976/Tensor_Flow_Alladdin_Persson/blob/main/2_Tensor_flow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print (tf.__version__)

2.12.0


In [2]:
import os
os.environ['TF_CPP_MIN_LOG_Level'] ='2'

# Initialization of *Tensors*

In [3]:
x= tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x= tf.constant(4.0, shape=(1,1))
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
x= tf.constant(4, shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [6]:
x= tf.constant([[1,2,3],[6,7,8]], dtype=tf.int64)
print(x)

tf.Tensor(
[[1 2 3]
 [6 7 8]], shape=(2, 3), dtype=int64)


In [7]:
x= tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [8]:
x= tf.zeros((4,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [9]:
x= tf.eye(4) # Identity Matrix
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [10]:
x= tf.random.normal((3,3),mean = 0, stddev=1) # Normal distribution
print(x)

tf.Tensor(
[[ 0.07581947  0.6423654  -0.3314324 ]
 [ 2.5281253  -2.759658   -0.47770074]
 [-0.43660372 -0.7754573  -1.1515232 ]], shape=(3, 3), dtype=float32)


In [11]:
x= tf.random.uniform((1,3), minval=0, maxval=1) # Uniform  distribution
print(x)

tf.Tensor([[0.30120063 0.11006629 0.5639429 ]], shape=(1, 3), dtype=float32)


In [12]:
x= tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [13]:
x= tf.range(start=1, limit=30, delta=2)
print(x)

tf.Tensor([ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29], shape=(15,), dtype=int32)


In [14]:
x= tf.cast(x,dtype=tf.float32)
print(x)

tf.Tensor([ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29.], shape=(15,), dtype=float32)


#Mathimatical Operations

In [15]:
x= tf.constant([1,2,3])
y =tf.constant([9,8,7])

z= tf.add(x,y)
z= x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [16]:
z= tf.subtract(x,y)
z=x-y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [17]:
z= tf.divide(x,y)
z= x/y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [18]:
z= tf.multiply(x,y)
z= x*y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [19]:
z= tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [20]:
z= tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [21]:
z= x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [23]:
x= tf.random.normal((2,3))
print(x)

y= tf.random.normal((3,4))
print(y)

print('----------------------')
z=tf.matmul(x,y)  # matmul -- > matrix multiplication
#z = x @ y # matrix multiplication
print(z)

tf.Tensor(
[[-0.00804807 -1.2523228  -0.20814012]
 [-0.00610397  1.1877117  -0.92682624]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.31847003  1.2155999  -0.35183364 -0.40646684]
 [ 1.6588895   1.4529405   1.1587529   0.28149712]
 [ 1.6226323   0.2490493  -0.9043225  -2.4647686 ]], shape=(3, 4), dtype=float32)
----------------------
tf.Tensor(
[[-2.412637   -1.881171   -1.2600753   0.16376325]
 [ 0.46832836  1.487429    2.2165618   2.6212306 ]], shape=(2, 4), dtype=float32)


# Indexing

In [28]:
x = tf.constant([0, 1, 2, 3, 4, 5, 6, 8])
print(x[:])

tf.Tensor([0 1 2 3 4 5 6 8], shape=(8,), dtype=int32)


In [29]:
print(x[1:])

tf.Tensor([1 2 3 4 5 6 8], shape=(7,), dtype=int32)


In [30]:
print(x[1:3])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [31]:
print(x[::2])

tf.Tensor([0 2 4 6], shape=(4,), dtype=int32)


In [32]:
print(x[::-1])

tf.Tensor([8 6 5 4 3 2 1 0], shape=(8,), dtype=int32)


In [35]:
indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)
print(x_indices)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [36]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
print(x[0, :]) #first row with all of its elements

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [37]:
print(x[0:2, :]) #first 2 rows with all of its elements

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#Reshaping Tensor

In [38]:
x = tf.range(9)
x = tf.reshape(x, (3, 3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [39]:
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
