<a href="https://colab.research.google.com/github/msaid1976/Tensor_Flow_Alladdin_Persson/blob/main/2_Tensor_flow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print (tf.__version__)

2.12.0


In [6]:
import os
os.environ['TF_CPP_MIN_LOG_Level'] ='2'

# Initialization of *Tensors*

In [7]:
x= tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
x= tf.constant(4.0, shape=(1,1))
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [10]:
x= tf.constant(4, shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [11]:
x= tf.constant([[1,2,3],[6,7,8]], dtype=tf.int64)
print(x)

tf.Tensor(
[[1 2 3]
 [6 7 8]], shape=(2, 3), dtype=int64)


In [12]:
x= tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x= tf.zeros((4,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [16]:
x= tf.eye(4) # Identity Matrix
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [18]:
x= tf.random.normal((3,3),mean = 0, stddev=1) # Normal distribution
print(x)

tf.Tensor(
[[ 0.7277074  -1.0100725   0.9492415 ]
 [-0.7919278   0.7674985  -0.9630984 ]
 [ 0.34556478  0.3383569  -1.7171632 ]], shape=(3, 3), dtype=float32)


In [19]:
x= tf.random.uniform((1,3), minval=0, maxval=1) # Uniform  distribution
print(x)

tf.Tensor([[0.11801445 0.9567642  0.61839664]], shape=(1, 3), dtype=float32)


In [20]:
x= tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [21]:
x= tf.range(start=1, limit=30, delta=2)
print(x)

tf.Tensor([ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29], shape=(15,), dtype=int32)


In [22]:
x= tf.cast(x,dtype=tf.float32)
print(x)

tf.Tensor([ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29.], shape=(15,), dtype=float32)


#Mathimatical Operations

In [ ]:
x= tf.constant([1,2,3])
y =tf.constant([9,8,7])

z= tf.add(x,y)
z= x+y
print(z)

In [ ]:
z= tf.subtract(x,y)
z=x-y
print(z)

In [ ]:
z= tf.divide(x,y)
z= x/y
print(z)

In [ ]:
z= tf.multiply(x,y)
z= x*y
print(z)

In [ ]:
z= tf.tensordot(x,y,axes=1)
print(z)

In [ ]:
z= tf.reduce_sum(x*y,axis=0)
print(z)

In [ ]:
z= x**5
print(z)

In [ ]:
x= tf.random.normal((2,3))
print(x)

y= tf.random.normal((3,4))
print(y)

print('----------------------')
 z=tf.matmul(x,y)  # matrix multiplication
#z = x @ y # matrix multiplication
print(z)

# Indexing

#Reshaping Tensor